name: Update Exchange Rates

on:
  schedule:
    - cron: '23 7 * * 4'
  workflow_dispatch:

jobs:
  generate-currency-rates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run generate_currency_rates.py
        run: |
          python scripts/generate_exchange_rates.py -o static/currency_rates.json
        env:
          EXCHANGE_RATE_API_KEY: ${{ secrets.EXCHANGE_RATE_API_KEY }}

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b update-currency-rates
          git add static/currency_rates.json
          git commit -m 'chore: update currency rates'

      - name: create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update currency rates'
          title: 'chore: update currency rates'
          body: 'This PR updates the currency rates.'
          branch: update-currency-rates
          base: main
   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}