name: Update Exchange Rates

on:
  schedule:
    - cron: '23 7 * * 4'
  workflow_dispatch:

jobs:
  generate-currency-rates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run generate_currency_rates.py
        run: |
          python scripts/generate_exchange_rates.py -o static/currency_rates.json
        env:
          EXCHANGE_RATE_API_KEY: ${{ secrets.EXCHANGE_RATE_API_KEY }}

      - name: Check for changes
        id: check_changes
        run: |
          # Configure git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Create or switch to the branch
          if git show-ref --verify --quiet refs/heads/chore/update-currency-rates; then
            git checkout chore/update-currency-rates
          else
            git checkout -b chore/update-currency-rates
          fi

          # Pull latest changes if the branch exists remotely
          if git ls-remote --exit-code --heads origin chore/update-currency-rates; then
            git pull --rebase origin chore/update-currency-rates
          fi

          # Add changes
          git add static/currency_rates.json

          # Check for changes
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
            echo "changes_detected=false" >> "$GITHUB_ENV"
          else
            # Commit and push changes
            git commit -m 'chore: update currency rates'
            git push origin chore/update-currency-rates
            echo "changes_detected=true" >> "$GITHUB_ENV"
          fi
